info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-28T17:02:27.753Z"}
info: Connected to the database. {"timestamp":"2022-07-28T17:02:27.841Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-28T17:04:37.122Z"}
info: Connected to the database. {"timestamp":"2022-07-28T17:04:37.172Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-28T17:15:46.114Z"}
info: Connected to the database. {"timestamp":"2022-07-28T17:15:46.167Z"}
error: 
    status - 500 
    message - TypeError: UserService.userRegistration is not a function
    at _callee$ (H:\NodeJS\fundooNotes\fundooNotes\src\controllers\/user.controller.js:12:37)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userRegistration (H:\NodeJS\fundooNotes\fundooNotes\src\controllers\/user.controller.js:10:31)
    at Layer.handle [as handle_request] (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\route.js:144:13)
    at newUserValidator (H:\NodeJS\fundooNotes\fundooNotes\src\validators\/user.validator.js:19:5)
    at Layer.handle [as handle_request] (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\route.js:114:3) 
    url - /api/v1/users/userRegistration 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-28T17:15:58.476Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-28T17:16:55.251Z"}
info: Connected to the database. {"timestamp":"2022-07-28T17:16:55.320Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-28T18:00:03.320Z"}
info: Connected to the database. {"timestamp":"2022-07-28T18:00:03.378Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: Fundoo_Notes.users index: email_1 dup key: { email: " rohitshinde@gmail.com " } 
      url - /api/v1/users/userRegistration 
      method - POST 
      IP - ::1
     {"timestamp":"2022-07-28T18:00:20.482Z"}
error: 
    status - 500 
    message - RangeError: Invalid status code: 11000
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.writeHead (node:_http_server:274:11)
    at ServerResponse.writeHead (H:\NodeJS\fundooNotes\fundooNotes\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:265:8)
    at write_ (node:_http_outgoing:766:9)
    at ServerResponse.end (node:_http_outgoing:855:5)
    at ServerResponse.send (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\response.js:278:15)
    at appErrorHandler (H:\NodeJS\fundooNotes\fundooNotes\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\index.js:326:13)
    at H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\index.js:346:12)
    at Immediate.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\index.js:280:10)
    at Immediate._onImmediate (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\index.js:646:15)
    at processImmediate (node:internal/timers:468:21) 
    url - /api/v1/users/userRegistration 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-28T18:00:20.522Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-28T18:11:45.742Z"}
info: Connected to the database. {"timestamp":"2022-07-28T18:11:45.808Z"}
error: 
    status - 500 
    message - Error: User already exist
    at _callee$ (H:\NodeJS\fundooNotes\fundooNotes\src\services\/user.service.js:9:9)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/userRegistration 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-28T18:11:58.484Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-28T18:19:06.948Z"}
info: Connected to the database. {"timestamp":"2022-07-28T18:19:07.008Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-28T18:22:18.677Z"}
info: Connected to the database. {"timestamp":"2022-07-28T18:22:18.736Z"}
error: 
    status - 500 
    message - Error: User not exist
    at _callee2$ (H:\NodeJS\fundooNotes\fundooNotes\src\services\/user.service.js:25:11)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-28T18:22:47.733Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-28T18:56:11.045Z"}
info: Connected to the database. {"timestamp":"2022-07-28T18:56:11.127Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-28T18:58:11.870Z"}
info: Connected to the database. {"timestamp":"2022-07-28T18:58:11.927Z"}
error: 
    status - 500 
    message - Error: password not match
    at _callee2$ (H:\NodeJS\fundooNotes\fundooNotes\src\services\/user.service.js:33:11)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-28T19:00:37.108Z"}
