info: ::1 - - [28/Jul/2022:17:15:58 +0000] "POST /api/v1/users/userRegistration HTTP/1.1" 500 81 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [28/Jul/2022:17:17:05 +0000] "POST /api/v1/users/userRegistration HTTP/1.1" 201 274 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [28/Jul/2022:18:00:20 +0000] "POST /api/v1/users/userRegistration HTTP/1.1" 500 61 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [28/Jul/2022:18:01:01 +0000] "POST /api/v1/users/userRegistration HTTP/1.1" 201 274 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [28/Jul/2022:18:11:58 +0000] "POST /api/v1/users/userRegistration HTTP/1.1" 500 53 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [28/Jul/2022:18:12:30 +0000] "POST /api/v1/users/userRegistration HTTP/1.1" 201 326 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [28/Jul/2022:18:22:47 +0000] "POST /api/v1/users/login HTTP/1.1" 500 49 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [28/Jul/2022:18:22:55 +0000] "POST /api/v1/users/login HTTP/1.1" 201 324 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [28/Jul/2022:19:00:06 +0000] "POST /api/v1/users/login HTTP/1.1" 201 253 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [28/Jul/2022:19:00:37 +0000] "POST /api/v1/users/login HTTP/1.1" 500 53 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [28/Jul/2022:19:00:46 +0000] "POST /api/v1/users/login HTTP/1.1" 201 253 "-" "PostmanRuntime/7.29.2"

error: uncaughtException: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>". {"date":"Fri Jul 29 2022 18:01:51 GMT+0530 (India Standard Time)","error":{"code":"ERR_UNHANDLED_REJECTION"},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1201558},"process":{"argv":["node","H:\\NodeJS\\fundooNotes\\fundooNotes\\src\\index.js"],"cwd":"H:\\NodeJS\\fundooNotes\\fundooNotes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18286977,"external":19936764,"heapTotal":48238592,"heapUsed":43455576,"rss":80703488},"pid":13564,"uid":null,"version":"v16.14.2"},"stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<Object>\".","trace":[]}
error: uncaughtException: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>". {"date":"Fri Jul 29 2022 18:03:24 GMT+0530 (India Standard Time)","error":{"code":"ERR_UNHANDLED_REJECTION"},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1201651},"process":{"argv":["node","H:\\NodeJS\\fundooNotes\\fundooNotes\\src\\index.js"],"cwd":"H:\\NodeJS\\fundooNotes\\fundooNotes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18374348,"external":19927986,"heapTotal":48762880,"heapUsed":43944216,"rss":81801216},"pid":14312,"uid":null,"version":"v16.14.2"},"stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<Object>\".","trace":[]}
error: uncaughtException: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>". {"date":"Fri Jul 29 2022 18:04:42 GMT+0530 (India Standard Time)","error":{"code":"ERR_UNHANDLED_REJECTION"},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1201729},"process":{"argv":["node","H:\\NodeJS\\fundooNotes\\fundooNotes\\src\\index.js"],"cwd":"H:\\NodeJS\\fundooNotes\\fundooNotes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":19354157,"external":22715172,"heapTotal":82386944,"heapUsed":54347656,"rss":116133888},"pid":16980,"uid":null,"version":"v16.14.2"},"stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<Object>\".","trace":[]}
info: ::1 - - [29/Jul/2022:12:37:48 +0000] "POST /api/v1/user/login HTTP/1.1" 404 47 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:12:38:44 +0000] "POST /api/v1/users/login HTTP/1.1" 201 253 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:12:44:00 +0000] "POST /api/v1/users/login HTTP/1.1" 201 253 "-" "PostmanRuntime/7.29.2"

error: uncaughtException: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>". {"date":"Fri Jul 29 2022 18:16:12 GMT+0530 (India Standard Time)","error":{"code":"ERR_UNHANDLED_REJECTION"},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1202419},"process":{"argv":["node","H:\\NodeJS\\fundooNotes\\fundooNotes\\src\\index.js"],"cwd":"H:\\NodeJS\\fundooNotes\\fundooNotes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18293219,"external":19938513,"heapTotal":47976448,"heapUsed":44192248,"rss":81256448},"pid":13564,"uid":null,"version":"v16.14.2"},"stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<Object>\".","trace":[]}
info: ::1 - - [29/Jul/2022:12:50:51 +0000] "POST /api/v1/note/addNote HTTP/1.1" 500 60 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:12:54:11 +0000] "POST /api/v1/note/addNote HTTP/1.1" 400 67 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:12:55:17 +0000] "POST /api/v1/users/login HTTP/1.1" 201 253 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:12:56:03 +0000] "POST /api/v1/users/login HTTP/1.1" 500 49 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:12:58:25 +0000] "POST /api/v1/users/login HTTP/1.1" 500 49 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:12:59:08 +0000] "POST /api/v1/users/login HTTP/1.1" 500 49 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:12:59:47 +0000] "POST /api/v1/users/login HTTP/1.1" 500 49 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:13:00:40 +0000] "POST /api/v1/users/login HTTP/1.1" 500 49 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:13:02:53 +0000] "POST /api/v1/users/login HTTP/1.1" 500 49 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:13:04:56 +0000] "POST /api/v1/users/login HTTP/1.1" 500 49 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:13:06:42 +0000] "POST /api/v1/users/userRegistration HTTP/1.1" 201 325 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:13:07:19 +0000] "POST /api/v1/users/login HTTP/1.1" 201 251 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:13:08:27 +0000] "POST /api/v1/note/addNote HTTP/1.1" 400 67 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:13:19:02 +0000] "POST /api/v1/users/login HTTP/1.1" 201 251 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:13:20:13 +0000] "POST /api/v1/note/addNote HTTP/1.1" 400 67 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:13:29:36 +0000] "POST /api/v1/users/login HTTP/1.1" 201 251 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:13:29:55 +0000] "POST /api/v1/users/login HTTP/1.1" 201 251 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:13:31:10 +0000] "POST /api/v1/users/login HTTP/1.1" 500 49 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:13:39:35 +0000] "POST /api/v1/users/login HTTP/1.1" 500 49 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:13:40:00 +0000] "POST /api/v1/users/login HTTP/1.1" 500 49 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:16:52:26 +0000] "POST /api/v1/users/login HTTP/1.1" 500 49 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:17:02:03 +0000] "POST /api/v1/users/login HTTP/1.1" 500 49 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:17:08:24 +0000] "POST /api/v1/users/userRegistration HTTP/1.1" 201 326 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:17:09:51 +0000] "POST /api/v1/users/userRegistration HTTP/1.1" 201 328 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:17:10:24 +0000] "POST /api/v1/users/login HTTP/1.1" 201 254 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:17:15:25 +0000] "POST /api/v1/users/login HTTP/1.1" 500 49 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:17:16:32 +0000] "POST /api/v1/users/login HTTP/1.1" 201 254 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:17:21:12 +0000] "POST /api/v1/users/login HTTP/1.1" 201 254 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:17:26:17 +0000] "POST /api/v1/note/addNote HTTP/1.1" 500 56 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:17:26:28 +0000] "POST /api/v1/users/login HTTP/1.1" 201 254 "-" "PostmanRuntime/7.29.2"

error: uncaughtException: data is not defined
ReferenceError: data is not defined
    at _callee$ (H:\NodeJS\fundooNotes\fundooNotes\src\middlewares\/auth.middleware.js:29:13)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {"date":"Fri Jul 29 2022 22:57:26 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1219293},"process":{"argv":["node","H:\\NodeJS\\fundooNotes\\fundooNotes\\src\\index.js"],"cwd":"H:\\NodeJS\\fundooNotes\\fundooNotes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18304618,"external":19858256,"heapTotal":48762880,"heapUsed":44335320,"rss":81735680},"pid":18248,"uid":null,"version":"v16.14.2"},"stack":"ReferenceError: data is not defined\n    at _callee$ (H:\\NodeJS\\fundooNotes\\fundooNotes\\src\\middlewares\\/auth.middleware.js:29:13)\n    at tryCatch (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","trace":[{"column":13,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\src\\middlewares\\/auth.middleware.js","function":"_callee$","line":29,"method":null,"native":false},{"column":17,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"tryCatch","line":86,"method":null,"native":false},{"column":24,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator._invoke","line":66,"method":"_invoke","native":false},{"column":21,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator.next","line":117,"method":"next","native":false},{"column":24,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"asyncGeneratorStep","line":3,"method":null,"native":false},{"column":9,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"_next","line":25,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":96,"method":null,"native":false}]}
info: ::1 - - [29/Jul/2022:17:34:48 +0000] "POST /api/v1/users/login HTTP/1.1" 201 254 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:17:35:57 +0000] "POST /api/v1/note/addNote HTTP/1.1" 400 43 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:17:36:36 +0000] "POST /api/v1/users/login HTTP/1.1" 201 254 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:17:38:31 +0000] "POST /api/v1/note/addNote HTTP/1.1" 400 43 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:17:41:05 +0000] "POST /api/v1/users/login HTTP/1.1" 201 254 "-" "PostmanRuntime/7.29.2"

error: uncaughtException: data is not defined
ReferenceError: data is not defined
    at _callee$ (H:\NodeJS\fundooNotes\fundooNotes\src\middlewares\/auth.middleware.js:29:12)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {"date":"Fri Jul 29 2022 23:11:57 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1220164},"process":{"argv":["node","H:\\NodeJS\\fundooNotes\\fundooNotes\\src\\index.js"],"cwd":"H:\\NodeJS\\fundooNotes\\fundooNotes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18304621,"external":19858259,"heapTotal":49025024,"heapUsed":44320536,"rss":81825792},"pid":13084,"uid":null,"version":"v16.14.2"},"stack":"ReferenceError: data is not defined\n    at _callee$ (H:\\NodeJS\\fundooNotes\\fundooNotes\\src\\middlewares\\/auth.middleware.js:29:12)\n    at tryCatch (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","trace":[{"column":12,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\src\\middlewares\\/auth.middleware.js","function":"_callee$","line":29,"method":null,"native":false},{"column":17,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"tryCatch","line":86,"method":null,"native":false},{"column":24,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator._invoke","line":66,"method":"_invoke","native":false},{"column":21,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator.next","line":117,"method":"next","native":false},{"column":24,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"asyncGeneratorStep","line":3,"method":null,"native":false},{"column":9,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"_next","line":25,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":96,"method":null,"native":false}]}
info: ::1 - - [29/Jul/2022:17:48:41 +0000] "POST /api/v1/users/login HTTP/1.1" 201 254 "-" "PostmanRuntime/7.29.2"

error: uncaughtException: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>". {"date":"Fri Jul 29 2022 23:20:18 GMT+0530 (India Standard Time)","error":{"code":"ERR_UNHANDLED_REJECTION"},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1220664},"process":{"argv":["node","H:\\NodeJS\\fundooNotes\\fundooNotes\\src\\index.js"],"cwd":"H:\\NodeJS\\fundooNotes\\fundooNotes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18284390,"external":19838028,"heapTotal":49287168,"heapUsed":44139384,"rss":82595840},"pid":15612,"uid":null,"version":"v16.14.2"},"stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<Object>\".","trace":[]}
info: ::1 - - [29/Jul/2022:17:55:04 +0000] "POST /api/v1/users/login HTTP/1.1" 201 254 "-" "PostmanRuntime/7.29.2"

error: uncaughtException: data is not defined
ReferenceError: data is not defined
    at _callee$ (H:\NodeJS\fundooNotes\fundooNotes\src\middlewares\/auth.middleware.js:29:13)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {"date":"Fri Jul 29 2022 23:26:26 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1221033},"process":{"argv":["node","H:\\NodeJS\\fundooNotes\\fundooNotes\\src\\index.js"],"cwd":"H:\\NodeJS\\fundooNotes\\fundooNotes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18295162,"external":19965625,"heapTotal":49025024,"heapUsed":44669600,"rss":81252352},"pid":13792,"uid":null,"version":"v16.14.2"},"stack":"ReferenceError: data is not defined\n    at _callee$ (H:\\NodeJS\\fundooNotes\\fundooNotes\\src\\middlewares\\/auth.middleware.js:29:13)\n    at tryCatch (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","trace":[{"column":13,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\src\\middlewares\\/auth.middleware.js","function":"_callee$","line":29,"method":null,"native":false},{"column":17,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"tryCatch","line":86,"method":null,"native":false},{"column":24,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator._invoke","line":66,"method":"_invoke","native":false},{"column":21,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator.next","line":117,"method":"next","native":false},{"column":24,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"asyncGeneratorStep","line":3,"method":null,"native":false},{"column":9,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"_next","line":25,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":96,"method":null,"native":false}]}
info: ::1 - - [29/Jul/2022:18:12:14 +0000] "POST /api/v1/users/login HTTP/1.1" 201 254 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:18:20:22 +0000] "POST /api/v1/users/login HTTP/1.1" 201 254 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:18:29:45 +0000] "POST /api/v1/users/login HTTP/1.1" 201 254 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:18:31:40 +0000] "POST /api/v1/note/addNote HTTP/1.1" 201 261 "-" "PostmanRuntime/7.29.2"

info: ::1 - - [29/Jul/2022:18:39:51 +0000] "POST /api/v1/note/addNote HTTP/1.1" 201 262 "-" "PostmanRuntime/7.29.2"

